name = "Re-Console Server Software"
author = "omo50"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0747b8310c9868f8a07a6eda494d440aabe1ef8f5f44f2c50be3cf18e0b1bd33"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
