name = "Re-Console Server Software"
author = "omo50"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2687d45808ffec132424154c2bde40e81f126cdfd2656cf56cc18d0161b1ec65"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
